export const greekLowercase = [
  { symbol: "α", caption: "alpha" },
  { symbol: "β", caption: "beta" },
  { symbol: "γ", caption: "gamma" },
  { symbol: "δ", caption: "delta" },
  { symbol: "ε", caption: "epsilon" },
  { symbol: "ζ", caption: "zeta" },
  { symbol: "η", caption: "eta" },
  { symbol: "θ", caption: "theta" },
  { symbol: "ι", caption: "iota" },
  { symbol: "κ", caption: "kappa" },
  { symbol: "λ", caption: "lambda" },
  { symbol: "μ", caption: "mu" },
  { symbol: "ν", caption: "nu" },
  { symbol: "ξ", caption: "xi" },
  { symbol: "ο", caption: "omicron" },
  { symbol: "π", caption: "pi" },
  { symbol: "ρ", caption: "rho" },
  { symbol: "σ", caption: "sigma" },
  { symbol: "τ", caption: "tau" },
  { symbol: "υ", caption: "upsilon" },
  { symbol: "ϕ", caption: "phi" },
  { symbol: "χ", caption: "chi" },
  { symbol: "ψ", caption: "psi" },
  { symbol: "ω", caption: "omega" },
];

export const greekUppercase = [
  { symbol: "Α", caption: "Alpha" },
  { symbol: "Β", caption: "Beta" },
  { symbol: "Γ", caption: "Gamma" },
  { symbol: "Δ", caption: "Delta" },
  { symbol: "Ε", caption: "Epsilon" },
  { symbol: "Ζ", caption: "Zeta" },
  { symbol: "Η", caption: "Eta" },
  { symbol: "Θ", caption: "Theta" },
  { symbol: "Ι", caption: "Iota" },
  { symbol: "Κ", caption: "Kappa" },
  { symbol: "Λ", caption: "Lambda" },
  { symbol: "Μ", caption: "Mu" },
  { symbol: "Ν", caption: "Nu" },
  { symbol: "Ξ", caption: "Xi" },
  { symbol: "Ο", caption: "Omicron" },
  { symbol: "Π", caption: "Pi" },
  { symbol: "Ρ", caption: "Rho" },
  { symbol: "Σ", caption: "Sigma" },
  { symbol: "Τ", caption: "Tau" },
  { symbol: "Υ", caption: "Upsilon" },
  { symbol: "Φ", caption: "Phi" },
  { symbol: "Χ", caption: "Chi" },
  { symbol: "Ψ", caption: "Psi" },
  { symbol: "Ω", caption: "Omega" },
];
