export const coordCmpdOptions = [
  { value: "mono", category: "quantifiers" },
  { value: "bis", category: "quantifiers" },
  { value: "di", category: "quantifiers" },
  { value: "hexa", category: "quantifiers" },
  { value: "penta", category: "quantifiers" },
  { value: "tetra", category: "quantifiers" },
  { value: "tetrakis", category: "quantifiers" },
  { value: "tris", category: "quantifiers" },
  { value: "tri", category: "quantifiers" },
  { value: "ammine", category: "ligands" },
  { value: "aqua", category: "ligands" },
  { value: "carbonyl", category: "ligands" },
  { value: "cyano", category: "ligands" },
  { value: "chloro", category: "ligands" },
  { value: "ethylenediamine", category: "ligands" },
  { value: "oxalato", category: "ligands" },
  { value: "oxo", category: "ligands" },
  { value: "chromium", category: "metals" },
  { value: "cobalt", category: "metals" },
  { value: "copper", category: "metals" },
  { value: "iron", category: "metals" },
  { value: "nickel", category: "metals" },
  { value: "(I)", category: "oxidation states" },
  { value: "(II)", category: "oxidation states" },
  { value: "(III)", category: "oxidation states" },
  { value: "(IV)", category: "oxidation states" },
  { value: "(V)", category: "oxidation states" },
  { value: "(VI)", category: "oxidation states" },
];
